# Generated by Django 5.2.1 on 2025-05-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_food_image_url_food_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
